CREATE TABLE OPTION_REQUEST_LOG 
(
  ID NUMBER(20) NOT NULL 
, TS TIMESTAMP 
, ADDRESS VARCHAR2(1000) 
, CONSTRAINT OPTION_RL_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE REQUES_LOG_SEQUENCE INCREMENT BY 1 START WITH 1;
